version: '3.8'

services:
  # Aplicação Flask
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=True
      - DATABASE_URI=postgresql://boathouse:boathouse@db:5432/boathouse
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - .env

  # Banco de dados PostgreSQL
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=boathouse
      - POSTGRES_USER=boathouse
      - POSTGRES_PASSWORD=boathouse
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Redis (para cache e sessões)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  # Nginx (proxy reverso)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    restart: unless-stopped

volumes:
  postgres_data: 