"""Add system config table

Revision ID: 7b70b91a643c
Revises: e7eeba7ffcf3
Create Date: 2025-07-05 06:52:30.357668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b70b91a643c'
down_revision = 'e7eeba7ffcf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('payment_reminder_days', sa.Integer(), nullable=True),
    sa.Column('payment_overdue_days', sa.Integer(), nullable=True),
    sa.Column('vessel_removal_days', sa.Integer(), nullable=True),
    sa.Column('payment_reminder_message', sa.Text(), nullable=True),
    sa.Column('payment_overdue_message', sa.Text(), nullable=True),
    sa.Column('vessel_removal_message', sa.Text(), nullable=True),
    sa.Column('send_email_notifications', sa.Boolean(), nullable=True),
    sa.Column('send_sms_notifications', sa.Boolean(), nullable=True),
    sa.Column('send_push_notifications', sa.Boolean(), nullable=True),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=True),
    sa.Column('maintenance_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.drop_table('_alembic_tmp_marinas')
    with op.batch_alter_table('marinas', schema=None) as batch_op:
        batch_op.alter_column('opening_hours',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'subscription_plans', ['plan_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('plan_id')

    with op.batch_alter_table('marinas', schema=None) as batch_op:
        batch_op.alter_column('opening_hours',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    op.create_table('_alembic_tmp_marinas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('uuid', sa.VARCHAR(length=36), nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('address', sa.VARCHAR(length=200), nullable=False),
    sa.Column('city', sa.VARCHAR(length=100), nullable=False),
    sa.Column('state', sa.VARCHAR(length=2), nullable=False),
    sa.Column('zip_code', sa.VARCHAR(length=10), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('website', sa.VARCHAR(length=200), nullable=True),
    sa.Column('latitude', sa.FLOAT(), nullable=True),
    sa.Column('longitude', sa.FLOAT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('max_berths', sa.INTEGER(), nullable=True),
    sa.Column('available_berths', sa.INTEGER(), nullable=True),
    sa.Column('opening_hours', sa.TEXT(), nullable=True),
    sa.Column('services', sa.TEXT(), nullable=True),
    sa.Column('logo_url', sa.VARCHAR(length=200), nullable=True),
    sa.Column('banner_url', sa.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('map_zoom', sa.INTEGER(), server_default=sa.text('(15)'), nullable=True),
    sa.Column('photos', sa.TEXT(), nullable=True),
    sa.Column('cover_photo_url', sa.VARCHAR(length=200), nullable=True),
    sa.Column('amenities', sa.TEXT(), nullable=True),
    sa.Column('rules', sa.TEXT(), nullable=True),
    sa.Column('contact_person', sa.VARCHAR(length=100), nullable=True),
    sa.Column('emergency_phone', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.drop_table('system_configs')
    # ### end Alembic commands ###
