"""Add subscription plans table

Revision ID: e7eeba7ffcf3
Revises: 2195a744a603
Create Date: 2025-07-05 06:39:08.981434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7eeba7ffcf3'
down_revision = '2195a744a603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('monthly_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('yearly_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_berths', sa.Integer(), nullable=True),
    sa.Column('max_services_per_month', sa.Integer(), nullable=True),
    sa.Column('max_documents', sa.Integer(), nullable=True),
    sa.Column('can_create_services', sa.Boolean(), nullable=True),
    sa.Column('can_upload_documents', sa.Boolean(), nullable=True),
    sa.Column('can_make_payments', sa.Boolean(), nullable=True),
    sa.Column('can_view_reports', sa.Boolean(), nullable=True),
    sa.Column('can_access_api', sa.Boolean(), nullable=True),
    sa.Column('is_test_plan', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('marinas', schema=None) as batch_op:
        batch_op.alter_column('opening_hours',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('plan_id')

    with op.batch_alter_table('marinas', schema=None) as batch_op:
        batch_op.alter_column('opening_hours',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
